### ISSUE TITLE
Current FSBID CDO Dashboard Workshop

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1154]
As a TalentMAP Designer
I will conduct a design studio on the current FSBID CDO Dashboard
so we can get a better understanding of their frustrations

## Acceptance Criteria
- In-person meeting at GSA
- Client presenting current CDO Dashboard on FSBID
- Takeaways on CDO Dashboard needs

## Design Studio
- [x] Schedule and Plan for workshop (second week of January?)
- [x] What do our user needs? (reference CDO Personas)
- [x] Have presentation of current CDO Dashboard or workflow on FSBID
- [x] Sketching session 1 | 10-15 minutes 
- [x]  Present Sketches 1
- [x] Sketching session 2 | 10-15 minutes 
- [x] Present Sketches 2
- [ ] Takeaways  | 20-25 mintutes

**Comment by burgwyn** [comment]
Closing
