### ISSUE TITLE
Map Visualization Working Sessions

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1186]
As a TalentMAP Designer
I will conduct brainstorming sessions to understand the UX for the map visualization
so that we have an understanding of its needs for our users

## Acceptance Criteria
- Map visualization brainstorming sessions
- Focused on Bureau Map visualization needs
- User Research strategy
- Sketch/paper prototyping designs

## Tasks
- [ ] Draft Plan and scope for Bureau map visualization effort
- [ ] **Brainstorm session 1**
- [ ] Create sketches/wireframes of ideas and concepts
- [ ] **Brainstorm session 2**
- [ ] Draft plan and scope for 2-3 Bureau paper prototype usability testing 
- [ ] Conduct paper prototype usability testing
- [ ] Synthesis testing data
- [ ] Present usability testing findings
- [ ] Iterate

**Comment by esgoodman** [comment]
No longer needed -- we are not doing the map visualization.
