### ISSUE TITLE
View Post Profiles

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#125]
As a bidding employee,
I want to be able to view all information about a post
So that I understand the conditions of life in and outside of work at post

**Acceptance Criteria**

* Out-linking to OBC post profiles via predetermined paths (specifically, *Post Info To Go*)
** Out-link opens a new tab
## Tasks
- [x]  Create Usability Plan for "Post Detail Experience"
- [x]  Create Workflow of new hypothesis experience 
- [x]  Create Sketch of Position Details page with "Post Detail" visualization (button, link, etc)
- [x]  Schedule Usability testing
- [x]  Conduct Usability Testing (2-3 participates)
- [ ]  Synthesize Data
- [ ]  Executive Summary

**Comment by burgwyn** [comment]
Team to identify new point of contact for gathering data

**Comment by wongperson** [comment]
Every post in OBC is alphabetically indexed to a number as the relative path. I think it may be as simple as getting the master list of the post pages to each path number.

**Comment by krisdelacruz** [comment]
**Ideation Session 12.14.17**

<img width="1001" alt="screen shot 2017-12-14 at 3 42 40 pm" src="https://user-images.githubusercontent.com/16211502/34013585-0ca33c9a-e0e6-11e7-9fe3-bb8272d3115e.png">

<img width="737" alt="screen shot 2017-12-14 at 3 42 45 pm" src="https://user-images.githubusercontent.com/16211502/34013591-1566fc4a-e0e6-11e7-9c99-5f5b85b3b63d.png">

**Comment by krisdelacruz** [comment]
DRAFT of user flow (mind the chicken scratch)

![post details userflows](https://user-images.githubusercontent.com/16211502/34018768-82038144-e0f9-11e7-82de-35898f1a409f.jpeg)

**Comment by wongperson** [comment]
@burgwyn Need to determine how an added post would affect key-value pair relationship between paths and the posts.

**Comment by burgwyn** [comment]
Removing #164 from the epic and closing
