### ISSUE TITLE
Phase 2 CDO Design Studio v2 "Their Journey"

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1360]
As a TalentMAP Design
I will need to draft a plan for a design studio with CDO's
so that I can better understand their day to day journey

## Tasks
- [x] Draft Plan and scope
- [x] Review Plan with clients
- [x] Schedule time and day for Design Studio
- [x] Facilitate Design Studio
- [ ] Synthesis Data
- [ ] Executive Summary

## Road Blocks
- Can only do 1-hour workshops with CDOs because of their limited time
