### ISSUE TITLE
Design - Studio FSBID Admin

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1434]
As a TalentMAP Designer
I will facilitate a Design Studio with the FSBID Admin
so that the team can have a deeper understanding of the Cycle management process

## Tasks
- [ ] Draft design studio plan
- [ ] Schedule time for FSBID Admin
- [ ] Faciliate Design studio 
- [ ] Synthesis data
- [ ] Create Cycle management process flow
- [ ] Create user stories

**Comment by krisdelacruz** [comment]
@esgoodman this is preliminary design studio session we had 2.12.18

![img_6649](https://user-images.githubusercontent.com/16211502/36222270-dd4f434c-118e-11e8-8a80-99a9ff415969.JPG)
