### ISSUE TITLE
Format alpha content consistently, following State conventions

### ISSUE THREAD

**Issue by esgoodman** [18F/State-TalentMAP#1603]
### Story
As a State Department employee visiting the TalentMAP site, 
I need to see content formatting that is consistent and that matches State Dept conventions
So that I have confidence in the professionalism and trustworthiness of the content

### Currently
We have content in the prototype and in wireframes that is inconsistently formatted and that does not match existing State Dept conventions. 

### Desired
Content formatting in alpha is consistent and matches State Dept styles. 

### Acceptance criteria
* State Department formatting conventions added to style guide 
* alpha.talentmap.us content matches style guide  

### Specific formatting questions
Add to this as you find them, and check off when fixed
- [ ] Date formatting (as per @BrownCA5 should be MM/DD/YYYY)
- [ ] Label hyphenation and visual style (eg is it `*Label:* Attribute` or `*Label* Attribute`)
- [ ] Heading formatting should be sentence case as per style guide.
- [ ] Grade formatting (Usability testing suggests our current style is confusing)
- [ ] Language proficiency (Currently inconsistently represented across the Dept; Robin will be sending examples of the most common formats)

**Comment by burgwyn** [comment]
[Date formatting](https://github.com/18F/State-TalentMAP/issues/1600) is [ready for review](https://github.com/18F/State-TalentMAP/pull/1602)

**Comment by esgoodman** [comment]
Robin is going to send information about grade and about language proficiency.

**Comment by cydneycappello** [comment]
Here is the information provided by Robin:

**Language Proficiency Level:**
Speak/Read
0/0
1/0
2/0
2/1
2/2
3/2
3/3
4/4

**Grades** (use the following order per Robin)
01
02
03
04
05
06
07
00
OC Counselor (FE-OC)
MC Minister-Counselor (FE-MC)
CM Career Minister (FE-CM)
