### ISSUE TITLE
User Interviews of Bureaus

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#565]
As a TalentMAP Designer
I need to conduct user interviews for Bureau reps
So that I am able to understand their needs

## Tasks
- [x] Collect Bureau frustration data from Bidder, CDO, and AO Data
- [ ] Gather Bureau Rep users (10 users)
- [x] Speak with Clients (Robin) to consolidate questions
- [ ] Create interview / activity guide
- [ ] Schedule Bureau Rep User Interviews
- [ ] Conduct User Interviews
- [ ] Synthesis Bureau User Interview Data
- [ ] Create report

**Comment by krisdelacruz** [comment]
**# Awareness**

- Chris and Robin are on the hunt to find the candidates from all 7 Bureaus
- Projected scheduling for interviews End of December or Beginning of January
-

**Comment by esgoodman** [comment]
@apbdevine @wongperson We need those names from the 7 bureaus to move forward with this!

**Comment by krisdelacruz** [comment]
@wongperson @esgoodman

**Comment by krisdelacruz** [comment]
A working draft of the bureau journey map for everyone's awareness. The interviews will help fill in the gaps.

![bureau rep journey map 1](https://user-images.githubusercontent.com/16211502/35415257-fa2a6588-01f2-11e8-84b0-6b31854e2594.jpg)

**Comment by krisdelacruz** [comment]
Brainstorming session

https://bahdigital.invisionapp.com/freehand/document/Su8kQfrMl

**Comment by esgoodman** [comment]
Interviews currently being scheduled; questions approved.
