### ISSUE TITLE
Historical assignments record

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#947]
As an authorized user, 
I want a centralized view of previous and current employee assignments
so I can evaluate a bidder based on the context of their professional history.

### Acceptance Criteria
- Authorized users can view an employee's assignment history, including current assignment
- Employees can have multiple assignments in their history
- Calculations, such as fair share, are driven by values stored in assignment history

Assignment consists of:
- Post name
- Post differential
- Assignment dates
- Grade
- Position title

## Steps
- [ ] Draft plan on design studio with CDO's and AO's "Historical Assignment Record"
- [ ] Brainstorm with Robin to evaluate what we need. Sketches, paper prototype
- [ ] Schedule time with CDO's (2 participates) and AO (2 Participates)
- [ ] Design Studio with CDO's and AO's
- [ ] Synthesis Data
- [ ] Present Findings, Executive Summary

**Comment by wongperson** [comment]
Let's continue talking to users evaluating these data areas for decision-making. Malleable model. @esgoodman @krisdelacruz

**Comment by afrasier** [comment]
Since assignments are linked to positions (and those to post, and so on) as the positions update over time, old assignment models will still be pointing to these updated positions. So on the backend we can have it save the historical data as strings when an assignment is completed; or we  could implement a history library. (I.e. so we could dive in and view the database "as it was on such and such date")

The history tracking uses more space than just storing the strings, but has more functionality.
