### ISSUE TITLE
Usability Testing on Bid Tracker

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#968]
As a TalentMAP Designer
I need to conduct usability testing on the Bid Tracker
So that I can capture user data on the sketches

## Tasks
- [x] Prepare plan
- [x] Prepare Paper Prototypes or wireframes
- [x] Gather 2-4 users to participate
- [x] Conduct Usability test
- [ ] Synthesis data
- [ ] Provide findings for the team
